#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
#  %%GAME_TITLE%% — Game Installer
#  Generated by CustomWolf Deploy System
# =============================================================================

GAME_TITLE='%%GAME_TITLE%%'
GAME_SLUG='%%GAME_SLUG%%'
TENANT_ID='%%TENANT_ID%%'
SVC_PREFIX='cwgame'
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEFAULT_PORT=8080

# ── Colours ───────────────────────────────────────────────────────────────────
R='\033[0;31m'; G='\033[0;32m'; Y='\033[1;33m'
C='\033[0;36m'; B='\033[1m'; DIM='\033[2m'; N='\033[0m'

# Use %b (not %s) so embedded \033[…m codes in message args are rendered.
step() { printf "\n%b▶%b %b\n"  "${B}${C}" "${N}" "$1"; }
ok()   { printf "  %b✓%b %b\n"  "${G}"     "${N}" "$1"; }
warn() { printf "  %b⚠%b %b\n"  "${Y}"     "${N}" "$1"; }
err()  { printf "  %b✗%b %b\n"  "${R}"     "${N}" "$1"; }

banner() {
  local t="${GAME_TITLE}"
  local w=62 tlen=${#t}
  local pad=$(( (w - tlen) / 2 ))
  local rpad=$(( w - pad - tlen ))
  printf "\n%b" "${C}"
  printf '╔'; printf '═%.0s' $(seq 1 $w); printf '╗\n'
  printf '║'; printf ' %.0s' $(seq 1 $w); printf '║\n'
  printf "║%b%b%*s%s%*s%b${C}║\n" "${B}" "${N}" "${pad}" "" "${t}" "${rpad}" "" "${N}"
  printf '║'; printf ' %.0s' $(seq 1 $w); printf '║\n'
  printf '╚'; printf '═%.0s' $(seq 1 $w); printf '╝\n'
  printf "%b\n" "${N}"
}

# ── Argument parsing ──────────────────────────────────────────────────────────
MODE=install
for arg in "$@"; do
  case "$arg" in
    --remove|remove) MODE=remove ;;
    --help|-h)       MODE=help   ;;
  esac
done

banner

if [[ "$MODE" == help ]]; then
  printf "  %bUsage:%b  bash install.sh [--remove] [--help]\n\n" "${B}" "${N}"
  printf "  (no args)   Install %b%s%b\n" "${B}" "${GAME_TITLE}" "${N}"
  printf "  --remove    Stop/remove running instances only — no install\n"
  printf "  --help      Show this message\n\n"
  exit 0
fi

# ── Init-system helpers ───────────────────────────────────────────────────────

_has_sudo() { timeout 3 sudo -n true 2>/dev/null; }

# True only when systemd is actually PID 1 (not just installed).
# Guards against Docker/LXC/WSL environments where systemctl exists but can't operate.
_systemd_active() {
  command -v systemctl &>/dev/null 2>&1 || return 1
  _has_sudo || return 1
  local pid1
  pid1="$(cat /proc/1/comm 2>/dev/null || true)"
  [[ "$pid1" == "systemd" ]] || return 1
}

# ── Collect running instances ─────────────────────────────────────────────────
declare -a INSTANCES=()

_scan_instances() {
  # Only query systemd if it is actually running
  if _systemd_active 2>/dev/null; then
    while IFS= read -r svc; do
      if [[ -n "$svc" ]]; then INSTANCES+=("systemd:${svc}"); fi
    done < <(timeout 5 systemctl list-units --type=service --no-legend 2>/dev/null \
      | awk '{print $1}' | grep "^${SVC_PREFIX}-${GAME_SLUG}" || true)
  fi
  if command -v pm2 &>/dev/null 2>&1; then
    while IFS= read -r name; do
      if [[ -n "$name" ]]; then INSTANCES+=("pm2:${name}"); fi
    done < <(timeout 5 pm2 list --no-color 2>/dev/null \
      | awk '{print $4}' | grep "^${SVC_PREFIX}-${GAME_SLUG}" || true)
  fi
  # Also look for a PID file left by the nohup fallback
  local pid_glob
  for pid_glob in "${HOME}/.${SVC_PREFIX}/${GAME_SLUG}-"*/game.pid; do
    [[ -f "$pid_glob" ]] || continue
    local pid port_dir
    pid="$(cat "$pid_glob" 2>/dev/null || true)"
    port_dir="$(basename "$(dirname "$pid_glob")")"
    if [[ -n "$pid" ]] && kill -0 "$pid" 2>/dev/null; then
      INSTANCES+=("nohup:${port_dir}:${pid}")
    fi
  done
  return 0
}

_stop_instance() {
  local type="${1%%:*}" rest="${1#*:}" name="${1##*:}"
  case "$type" in
    systemd)
      sudo systemctl stop    "$name" 2>/dev/null && ok "Stopped service $name"    || warn "Could not stop $name"
      sudo systemctl disable "$name" 2>/dev/null || true
      sudo rm -f "/etc/systemd/system/${name}.service" 2>/dev/null || true
      sudo systemctl daemon-reload 2>/dev/null || true
      ;;
    pm2)
      pm2 delete "$name" 2>/dev/null && ok "Removed pm2 process $name" || warn "Could not remove $name"
      ;;
    nohup)
      # rest = "port_dir:pid"
      local pid="${rest##*:}" port_dir="${rest%%:*}"
      kill "$pid" 2>/dev/null && ok "Killed process $pid ($port_dir)" || warn "Could not kill $pid"
      rm -f "${HOME}/.${SVC_PREFIX}/${port_dir}/game.pid" 2>/dev/null || true
      ;;
  esac
}

# ── Remove-only mode ──────────────────────────────────────────────────────────
if [[ "$MODE" == remove ]]; then
  step "Scanning for running instances of ${B}${GAME_TITLE}${N}..."
  _scan_instances

  if [[ ${#INSTANCES[@]} -eq 0 ]]; then
    warn "No running instances of ${GAME_TITLE} found."
    exit 0
  fi

  printf "\n  Found %d instance(s):\n\n" "${#INSTANCES[@]}"
  declare -A IMAP=()
  local_i=1
  for inst in "${INSTANCES[@]}"; do
    printf "    %b[%d]%b  %s\n" "${B}" "${local_i}" "${N}" "${inst}"
    IMAP[$local_i]="$inst"
    (( local_i++ ))
  done
  printf "    %b[a]%b  Remove all\n\n" "${B}" "${N}"

  read -rp "  Select instance(s) to remove [1-$((local_i-1)) or a]: " sel
  if [[ "$sel" == a || "$sel" == all ]]; then
    for inst in "${INSTANCES[@]}"; do _stop_instance "$inst"; done
  else
    IFS=',' read -ra picks <<< "$sel"
    for p in "${picks[@]}"; do
      p="${p// /}"
      [[ -n "${IMAP[$p]+x}" ]] && _stop_instance "${IMAP[$p]}" || warn "Unknown selection: $p"
    done
  fi
  printf "\n"; ok "Done."; printf "\n"
  exit 0
fi

# ── Requirements check ────────────────────────────────────────────────────────
step "Checking requirements..."

if ! command -v node &>/dev/null; then
  err "Node.js is not installed."
  printf "\n  Install Node.js 22+ from %bhttps://nodejs.org%b\n" "${C}" "${N}"
  printf "  Quick install: %bcurl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash - && sudo apt-get install -y nodejs%b\n\n" "${DIM}" "${N}"
  exit 1
fi

node_ver="$(node -e "process.stdout.write(process.version.replace('v','').split('.')[0])")"
if [[ "$node_ver" -lt 22 ]]; then
  err "Node.js 22+ required. Found: $(node --version)"
  printf "  Upgrade: %bnvm install 22 && nvm use 22%b\n" "${DIM}" "${N}"
  exit 1
fi
ok "Node.js $(node --version)"

if ! command -v npm &>/dev/null; then
  err "npm not found (normally bundled with Node.js)."
  exit 1
fi
ok "npm $(npm --version)"

# ── Detect existing installations ─────────────────────────────────────────────
step "Checking for existing installations..."
_scan_instances

if [[ ${#INSTANCES[@]} -gt 0 ]]; then
  warn "Found ${#INSTANCES[@]} existing installation(s) of ${B}${GAME_TITLE}${N}:"
  for inst in "${INSTANCES[@]}"; do
    printf "    •  %s\n" "$inst"
  done

  printf "\n  %bWhat would you like to do?%b\n" "${B}" "${N}"
  printf "    %b[1]%b  Replace — stop existing and install fresh\n" "${B}" "${N}"
  printf "    %b[2]%b  Keep alongside — install on a different port\n" "${B}" "${N}"
  printf "    %b[3]%b  Cancel\n\n" "${B}" "${N}"
  read -rp "  Your choice [1/2/3]: " action_choice

  case "$action_choice" in
    1)
      step "Stopping existing installations..."
      for inst in "${INSTANCES[@]}"; do _stop_instance "$inst"; done
      ;;
    2) ok "Will install alongside existing instance(s)." ;;
    3) printf "\n  Cancelled.\n\n"; exit 0 ;;
    *) err "Invalid choice."; exit 1 ;;
  esac
fi

# ── Port selection ─────────────────────────────────────────────────────────────
step "Choosing a port..."

find_free_port() {
  local port="$1"
  while true; do
    local in_use=false
    if command -v lsof &>/dev/null 2>&1; then
      lsof -iTCP:"$port" -sTCP:LISTEN &>/dev/null 2>&1 && in_use=true
    elif command -v ss &>/dev/null 2>&1; then
      ss -tlnp 2>/dev/null | grep -q ":${port} " && in_use=true
    fi
    $in_use || { echo "$port"; return; }
    (( port++ ))
  done
}

REC_PORT="$(find_free_port $DEFAULT_PORT)"
printf "  Suggested port: %b%s%b\n" "${B}" "${REC_PORT}" "${N}"
read -rp "  Press Enter to accept, or type a different port: " PORT_INPUT
PORT="${PORT_INPUT:-$REC_PORT}"

if ! [[ "$PORT" =~ ^[0-9]+$ ]] || [[ "$PORT" -lt 1024 ]] || [[ "$PORT" -gt 65535 ]]; then
  warn "Invalid port — using $REC_PORT."
  PORT="$REC_PORT"
fi
ok "Port: ${PORT}"

# ── Install files ─────────────────────────────────────────────────────────────
INSTALL_DIR="${HOME}/.${SVC_PREFIX}/${GAME_SLUG}-${PORT}"
SVC_NAME="${SVC_PREFIX}-${GAME_SLUG}-${PORT}"

step "Installing to ${B}${INSTALL_DIR}${N}..."
mkdir -p "$INSTALL_DIR"
cp -r "${SCRIPT_DIR}/public"       "${INSTALL_DIR}/"
cp -r "${SCRIPT_DIR}/tenant"       "${INSTALL_DIR}/"
cp    "${SCRIPT_DIR}/server.mjs"   "${INSTALL_DIR}/"
cp    "${SCRIPT_DIR}/package.json" "${INSTALL_DIR}/"
mkdir -p "${INSTALL_DIR}/tenant/saves"
ok "Files copied"

step "Installing Node.js dependencies..."
( cd "$INSTALL_DIR" && npm install --omit=dev --silent )
ok "Dependencies ready"

# ── Service setup ──────────────────────────────────────────────────────────────
step "Setting up auto-start..."

if _systemd_active; then
  # systemd is available and running as PID 1
  SVC_FILE="/etc/systemd/system/${SVC_NAME}.service"
  sudo tee "$SVC_FILE" > /dev/null <<UNIT
[Unit]
Description=${GAME_TITLE} game server (port ${PORT})
After=network.target

[Service]
Type=simple
User=$(whoami)
WorkingDirectory=${INSTALL_DIR}
Environment=PORT=${PORT}
ExecStart=$(command -v node) ${INSTALL_DIR}/server.mjs
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
UNIT
  sudo systemctl daemon-reload
  sudo systemctl enable "${SVC_NAME}" --quiet
  sudo systemctl start  "${SVC_NAME}"
  ok "systemd service ${SVC_NAME} enabled and started"

elif command -v pm2 &>/dev/null; then
  PORT="${PORT}" pm2 start "${INSTALL_DIR}/server.mjs" \
    --name "${SVC_NAME}" \
    --restart-delay 5000 \
    --silent
  pm2 save --silent 2>/dev/null || true
  ok "pm2 process ${SVC_NAME} started"

else
  nohup env PORT="${PORT}" node "${INSTALL_DIR}/server.mjs" \
    > "${INSTALL_DIR}/game.log" 2>&1 &
  echo "$!" > "${INSTALL_DIR}/game.pid"
  ok "Started (PID $(cat "${INSTALL_DIR}/game.pid"))"
  warn "No init system found — game will not auto-restart on reboot."
  printf "  Restart: %bPORT=%s node %s/server.mjs%b\n" "${DIM}" "${PORT}" "${INSTALL_DIR}" "${N}"
  printf "  Stop:    %bkill \$(cat %s/game.pid)%b\n"    "${DIM}" "${INSTALL_DIR}" "${N}"
fi

# ── Done ──────────────────────────────────────────────────────────────────────
HOST_IP="$(hostname -I 2>/dev/null | awk '{print $1}' || echo localhost)"

printf "\n"
printf "%b╔══════════════════════════════════════════════════════════════╗%b\n" "${G}" "${N}"
printf "%b║              Installation complete — enjoy!                  ║%b\n" "${G}" "${N}"
printf "%b╚══════════════════════════════════════════════════════════════╝%b\n" "${G}" "${N}"
printf "\n  %b%s%b is running\n\n" "${B}" "${GAME_TITLE}" "${N}"
printf "  %bLocal:%b   %bhttp://localhost:%s/game/%s%b\n" "${B}" "${N}" "${C}" "${PORT}" "${TENANT_ID}" "${N}"
printf "  %bNetwork:%b %bhttp://%s:%s/game/%s%b\n"        "${B}" "${N}" "${C}" "${HOST_IP}" "${PORT}" "${TENANT_ID}" "${N}"
printf "\n  %bTo remove this installation:%b\n"            "${DIM}" "${N}"
printf "  %b  bash install.sh --remove%b\n\n"              "${DIM}" "${N}"
